export const USER_TABLE = 'users'
export const ORGANIZATION_TABLE = 'organizations'
export const CHARACTERISTIC_TABLE = 'characteristics'
export const GYM_TABLE = 'gyms'
export const TRAINING_TABLE = 'trainings'
