export const USER_TABLE = 'users'
export const TRAINER_LEARNER_TABLE = 'trainer_learner'
export const ORGANIZATION_TABLE = 'organizations'
export const CHARACTERISTIC_TABLE = 'characteristics'
export const GYM_TABLE = 'gyms'
export const TRAINER_GYM_TABLE = 'trainer_gym'
export const TRAINING_TABLE = 'trainings'
export const ABONEMENT_TABLE = 'abonements'
export const LEARNER_ABONEMENT_TABLE = 'learner_abonement'

export const TRAINERS_RELATION = 'trainers'
export const LEARNERS_RELATION = 'learners'
export const LEARNER_ABONEMENT_RELATION = 'learnerAbonements'
export const GYMS_RELATION = 'gyms'
export const GYM_RELATION = 'gym'

export const LEARNER_RELATION = 'learner'
export const ABONEMENT_RELATION = 'abonement'
export const CREATOR_RELATION = 'creator'
